name: languo
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=2.18.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  firebase_core: ^3.15.2
  firebase_auth: ^5.3.3
  cloud_firestore: ^5.4.4
  firebase_storage: ^12.3.3
  cloud_functions: ^5.2.3

  google_sign_in: ^6.3.0
  provider: ^6.1.1
  flutter_facebook_auth: ^6.0.3
  intl: ^0.19.0
  google_maps_flutter: ^2.6.1
  geolocator: ^10.0.0

  fl_chart: ^1.1.1

  mobile_scanner: ^5.2.3
  permission_handler: ^11.3.1
  qr_flutter: ^4.1.0
  cupertino_icons: ^1.0.2
  image_picker: ^1.2.1
  crypto: ^3.0.3
  file_picker: ^10.3.7
  url_launcher: ^6.3.2
  rxdart: ^0.27.7
  universal_html: ^2.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/google.png
    - assets/facebook.png
    - assets/bgbelakang.png
    - assets/bgdepan.png
    - assets/logosipres.png
    - assets/book_icon.png
    - assets/jti.png
